### ISSUE TITLE
Fix travis notifications and pre-commit hooks

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/metadata-schema#1025]
**Description**

 

As a DCP member that commits into this repository, I would like to add changes to `.travis.yml`, `src/add_docs.sh` and `.pre-commit-config.yaml`, in order to fix some bugs found.

**Acceptance Criteria**

 
 
- [ ] `.travis.yml`: Change current document to have this at the end:
```
notifications:
  slack:
    rooms:
      - secure: UfBGxFNJsQaXqZxgdMT0SFEsKlaMT+J4XlKIO/Cwaomex3LkkT4TPW0S1qYehgzGeY8SBGVjilod8nhLl2+eRs3Fm5Q2YtxG0+fHLQOEHbnkpTcRjhHGJav51/msTLWsj5lXKveMNOaeFB1Q5qGGIQWsqMmwEyuDRVaAhnWAn2ueisOvXQrsCbauSvrhg8wfQ5fc4oteVyj9QvIY2+U2ZiVEr8PZGjs+y8LqPUeIrkBbGJFd8DdWoKATAvVnKZirEzF5pIBlAUsQjgYcCef9Cl/kqcvO9yUjbYh5MPlK/j1UEOnif7lKBcM+BIv1m1AaoaDtbgdJFbVW8wKVLp1zrMvsJpKMm3VFBsfU2MruQgJA8F+QgtVX8jJQXINUuhYD8U6pfrf/AFW1LJmy4R6iTkHLVBpkrPhf8A99Zymur7Bbn2eZGGgmJ2E0At/a18Kh7HMLVRsB8dy9hi42aiLDiJOqCDcZva7Rb8KgbWoplXrdFSEzh+xHJmDMnXiumDO0iVhNLH+Yx5Fpkrh+WSLaqCPFfYA0suOojGXr+waDRyW+HIfuS4bc0IpVhwJ+nR1SYzKkG5X0N1d1XUxkmNHDIKc1wFcxCKRAJDz9JHTWiM2nRZeOs+VCzqSpn5nApw/Gk9YmFhIir/GK1eaN1sa76wCsaCT8m7DpuoWkTryGSpU=
    on_failure: change
    on_success: change
```
- [ ] `src/add_docs.sh`: Call `src/human_readable_json.py` from inside the executable
- [ ] `src/add_docs.sh`: Change name to its new function.
