### ISSUE TITLE
Overhaul imaging_protocol.json 

### ISSUE THREAD

**Issue by dosumis** [HumanCellAtlas/metadata-schema#368]
**For which schema is a change/update being suggested?**

type/protocol/imaging/imaging_protocol.json 

**What should the change/update be?**

This is an umbrella ticket covering a number of changes including

* Updates to field names
* Updates to field / schema descriptions
* New schemas modules
* New schema fields
* Refactoring to move some schema fields

**Assumptions:** 

Imaging experiments involve the collection of images of a sample in one or more channels, each capturing different signals with information about different features of the sample.   Those signals can come from a variety of different types of probes including:  a fluorescent dye that marks nuclei (e.g. DAPI); an antibody against a marker of some cell feature (actin cytoskeleton; presynapse); an antisense flourescent nucleic acid probe that detects transcripts (smFISH).  More recently, techniques have been developed that massively increase the number of features that can be probed.  These typically involved multiple channels and multiple rounds of probe hybridisation.  Signals are then decoded using a code book that translates signals from channels + hybridization rounds to detected genes.

These different approaches may be combined.  For example, the SpaceTx project uses a variety of spatial transciptomics techniques, each combined with imaging of nuclei (using the fluorescent dye DAPI) and a secondary background stain (antibody based?) that detects some other aspect of subcellular anatomy. 

**Modelling strategy**

1. Based on the assumptions outlined in the previous section, it seems safe to conclude that we need a modular schema that collects general microscopy information that covers all channels (e.g. imaging type: confocal microscopy) and allows this general information to be combined with information about one or more simple channels (e.g. DAPI channel)  + a multi-channel assay (e.g. MerFish) in each case recording key information about what is being detected and how.
2. We have provisionally decided to move fields pertaining to imaging sample prep into a new imaging_sample_prep_protocol.json. Discussion of this decision would be most welcome.

**Why is the change requested?**

This is a first attempt at a general schema for imaging data.  It is informed by the needs of the SpaceTx project, but intended to provide a general framework for capturing imaging experiment metadata.

**What new field(s) need to be changed/added?**

Fields in the current imaging_protocol.json require review.  Some will be kept, some will be moved to down to modules,  others will be moved to a new imaging sample prep schema.

Fields to keep: 

field_microns; field_resolution ? (These will need expert review in future).

General fields:

```yaml
description: ""
required: [microscopy_type]
properties:
    microscopy_type:  # replaces 'microscope' field, which is currently a simple enum.
        description: >
           The type of microscopy used for imaging (e.g. confocal; two photon, 
           super-resolution)
        type: object,
        $ref: module/ontology/microscopy_ontology.json  # TBA - will use imports from FBbi
    simple_channel_assays:
         type: array
         value: { $ref : module/imaging/single_channel_assay.json  }
    multi_channel_assay:
 # 1. Struggling to think of name that copes with this group's allergy to the term
 # 'assay' as understood by biologists
 # 2. It seems likely that other multi-channel, multiplexed techniques will follow
 #  that are not STx so keeping this open.
        type: object
        value: { OneOf: [$ref: module/imaging/spatial_transcriptomics.json] } 
    microscope_model:
        type: String
    objective:
       type: String
...     # Many other possible general fields here.
```

module/imaging/single_channel_assay.json

```yaml
description: "A module for capturing information about a single channel used to collect a single signal type."
required: [protocol_type] 
properties: 
    channel_identifier:
        description: > 
               An identifier used for this channel within the experiment, 
               e.g. 'red channel' or channel 1.  This should align with the way channels are 
               referenced in file_names or file manifests.
    protocol_type:
        description: >
             The type of protocol used to assay for the signal in this channel, 
              e.g.  smFISH; antibody stain; fluorescent dye.  This field is required.
        type: object
        $ref: 
    reagent:
        description: >
             The specific reagent used to detect single in this channel.
              Examples include, a fluorescent probe used in smFISH;
              a comercial antibody; a commercial fluorescent dye.
        type: object 
        $ref: module/process/purchased_reagents.json
    target_gene_product:
       description: "Gene product targeted by reagent." 
       type:  String # Questions: Should this be an array. Should we allow for collection of gene/transcript/protein identifiers?
    target structure:  
            ontology: GO-subcellular component # Allow for anatomy here?
```

module/imaging/spatial_transcriptomics.json

```yaml
description: >
    A module for capturing a general description of a spatial transcriptomics 
    experiments.
required: [spatial_transcriptomics_protocol_type,  target_gene_list]
properties:
    spatial_transcriptomics_protocol_type:
        description: > 
             The type of spatial transcriptomics protocol used, e.g. MerFISH, seqFISH etc
        type: object
        $ref: module/ontology/STx_ontology.json # TBA
   target_gene_list:
        type: array
        value: string # Should we allow for collection of gene/transcript/protein identifiers?
# Many possible additional fields dealing with hyb conditions, microfluidics etc.
```

imaging_sample_prep_protocol.json # Consider keeping this all under microscopy ?

```yaml
description: > 
       A schema for collecting information on how a sample was prepared and mounted
       for imaging
required: []
properties: 
    fixative: 
    mounting medium:
    embedding: 
    clearing agent: 
    overview_image: 
        description: >
              Pointer/link to an overview image of the imaged sample.  
              Where multiple fields of view are collected during an assay, 
              it can be useful to have a lower resolution overview-image 
              covering the whole sample.  This field is for capturing a pointer/link 
              to such an image.
        type: string
    structures_within_sample:
      description: > 
          Anatomical structures/boundaries that are present within the sample. 
          These are potentially useful for indexed search and as landmarks for use 
          in image analysis (e.g. registration and segmentation).
      type: array
      value: { $ref: /modules/ontology/organ_part.json }
```
    
image_files.json

```yaml
   # TBA: Generic schema and / core stuff.
   description: >
        Pointers to one or more image files or a data manifest that aggregates them.
   required: []
   properties:
     image_file_set:
         type: object
         $ref: /modules/ ... image_file_set.json
     data_manifest:
         type: string 
         description:  > 
              A JSON file that organises a set of image files from a single imaging experiment.
         # SpaceTx produces one of these.        
    pipeline_recipe: # Does this belong here?
        type: string 
         description:  > 
              A JSON file that describes an analysis pipeline for images.
```

image_file_set.json 

\# Stub 
We need a way to aggregate relatively simple image file data from a single experiment.  Perhaps just collecting channel name and filename/pointer for each?

Consider what we might take from  https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/type/file/sequence_file.json

**Comment by joshmoore** [comment]
A few initial comments:

> We have provisionally decided to move fields pertaining to imaging sample prep into a new imaging_sample_prep_protocol.json. Discussion of this decision would be most welcome.

:+1:

> TBA - will use imports from FBbi

See https://github.com/EBISPOT/efo/issues/47#issuecomment-342826257 

> Perhaps just collecting channel name and filename/pointer for each?

I’m not sure I follow, but in the general case, I don’t think this will work.

>        Pointers to one or more image files or a data manifest that aggregates them.


Do you have an example of similar data_manifests in other domains? I’ve tried modelling this for an existing dataset in the IDR with all files listed. The json clocks in at 500MB. The alternative is a one-file-per-assay representation a la https://github.com/IDR/idr-metadata/blob/master/idr0016-wawer-bioactivecompoundprofiling/screenA/idr0016-screenA-plates.tsv assuming it’s ok to delegate the calculation of the fileset to a library.

>    pipeline_recipe: # Does this belong here?


My suggestion would be no since there is little agreement on standardized pipelines.

----

I was hoping to represent the IDR & OME metadata in json as a comparison here, but my (HCA-)jsonschema-fu still needs work. If it’s still of use, I can provide an abstract representation of the metadata we’re tracking (perhaps a simplified representation of [the docs](https://docs.openmicroscopy.org/ome-model/5.6.1/specifications/index.html#definitions-of-values-stored)).

**Comment by dosumis** [comment]
Hi Josh,

Thanks for the comments

First data we need to support = SpaceTx.  They have there own data_manifest and pipeline_recipe in JSON.  We need hooks for these somewhere.  The schema needs to be able to abstract this to point to other file aggregation systems (OME/IDR) and (probably) some simple generic specification that we define.  

We need ways to map channel metadata or multi-channel assay data to image files.  I think ideally the links to channel files (or agregations of them across hybs) would be in simple_channel.json or /spatial_transcriptomics.json as appropriate - that way we wouldn't need to key on channel identifiers. But this would be different from how sequencing is modelled.  It could also potentially => deeper nesting, which doesn't work well when trying to support spec of metadata in spreadsheets.

**Comment by ambrosejcarr** [comment]
David, this looks really great! I've added some comments, but mostly I wanted to continue our conversation about single- vs. multi-channel experiments and whether they require separation. 

# Single- vs. multi-channel experiments

I think coded and non-coded image-based transcriptomics and proteomics experiments are best described using a unified framework that revolves around the coding strategy used. In spaceTx we define a `codebook` object that specifies how channels and imaging rounds map to targets, and I think that could be nicely generalized here. 

The below example describes a simple experiment with two imaging channels and two hybridization rounds. While it's appropriate for spaceTx to call these hybridization rounds, For the purpose of generality, I will refer to them as imaging rounds for the rest of this response. 

```json
codebook.json
[
  {
    "codeword": [
      { "h": 0, "c": 0, "v": 1 },
      { "h": 0, "c": 1, "v": 1 },
    ],
    "gene_name": "SCUBE2"
  },
  {
    "codeword": [
      { "h": 0, "c": 0, "v": 1 },
      { "h": 1, "c": 1, "v": 1 }
    ],
    "gene_name": "BRCA"
  }
]
```

I recall that two chief concerns about using this approach to specify non-coded experiments were the increased complexity for simple experiments like smFISH and a lack of generality for non-transcriptomic approaches. I wasn't able to fully articulate this at the time, but I don't believe either of these are significant impediments and explain why below. 

## Single-molecule FISH

Here's what the coding scheme might look like for an smFISH experiment. 

```json
codebook.json
[
  {
    "codeword": [
      { "h": 0, "c": 0, "v": 1 },
    ],
    "gene_name": "SCUBE2"
  },
  {
    "codeword": [
      { "h": 0, "c": 1, "v": 1 },
    ],
    "gene_name": "BRCA"
  }
]
```

I would argue that the concept of an imaging round is a comfortable one for an experimentalist doing an smFISH experiment. If need be we could relax the requirements on the codebook such that when omitted, `h = 0` and `v = 1`. Then the codebook becomes: 

```json
codebook.json
[
  {
    "codeword": [
      { "c": 0 }
    ],
    "gene_name": "SCUBE2"
  },
  {
    "codeword": [
      { "c": 1 }
    ],
    "gene_name": "BRCA"
  }
]
```

## Generalizing to other imaging targets
To generalize this concept to any other strategy, all we would need to do is exchange `gene_name` for a more general term like `target`, and now it works for nuclear stains, the actin cytoskeleton, or proteomics experiments. 

# Other comments

> single_channel_assay.properties

This field is great, and should be recorder for every channel in either smFISH, multiplex or non-transcriptomic approaches -- we always want to know what the channels are. 

```yaml
 pipeline_recipe: # Does this belong here?
        type: string 
         description:  > 
              A JSON file that describes an analysis pipeline for images.
```

`pipeline_recipe` is pretty uncertain right now -- we have to figure out a lot of things on the secondary analysis side before we'll know if it's necessary. If it is, then we will probably want to include it. I would omit this for now but keep the idea around, as users will not be able to fill this value. 


> We need a way to aggregate relatively simple image file data from a single experiment. Perhaps just collecting channel name and filename/pointer for each?

If I'm understanding that you need a way to map images to their channels and hybridization rounds, you can extract this from the spaceTx manifest that the user will provide. See [experiment.json](https://docs.google.com/document/d/12V-BQF-wh1GDBXwUH2hQrPhw6n0oQqENPK-YHGv59w4/edit?ts=5b47c9da#heading=h.uonepw1m6b3d) and [hybridization.json](https://docs.google.com/document/d/12V-BQF-wh1GDBXwUH2hQrPhw6n0oQqENPK-YHGv59w4/edit?ts=5b47c9da#heading=h.ig9y3ngljp3r)
